### ISSUE TITLE
Duplicated name-entries.

### ISSUE THREAD

**Issue by Ricky-Tigg** [CanonicalLtd/lightdm#16]
Hi.  Investigation made upon suggested links –one at a time– present on Red Hat Bugzilla – [1518343](https://bugzilla.redhat.com/show_bug.cgi?id=1518343).

**Comment by robert-ancell** [comment]
This seems to be due to there being two sessions with the same name - one X and one Wayland. It would have to be up to the greeter to recognize these are different and label them as such. The logic should probably be if multiple sessions have the same name then make the labels "GNOME (X)" and "GNOME (Wayland)" by checking the value of `lightdm_session_get_session_type ()`.
