### ISSUE TITLE
Remove Mir support

### ISSUE THREAD

**Issue by tintou** [CanonicalLtd/lightdm#24]
You know why…

**Comment by robert-ancell** [comment]
I've been meaning to ask on the mailing list if anyone is affected by this. I was waiting for Ubuntu 18.04 to be released so now is the time (i.e. remove in lightdm 1.28).

**Comment by robert-ancell** [comment]
https://lists.freedesktop.org/archives/lightdm/2018-June/001138.html

**Comment by AlanGriffiths** [comment]
Hi, I've just been asked about this in the UBports group. I'm not sure what specific Mir support in lightdm has, but presume:
1. this will only affect downstream projects running Mir as a (mir-protocol) system compositor?
2. Ubuntu 18.04 is likely to remain on lightdm 1.26?

**Comment by khurshid-alam** [comment]
Ubport uses it. And MIr is still being developed. So a big no from me.

**Comment by RAOF** [comment]
My understanding of the Mir support in LightDM is to spawn & talk to `unity-system-compositor` before running Unity8 on top of that?

My understanding is that Ubports is moving away from using u-s-c (particularly once we support running without root privileges, via logind support).

**Comment by robert-ancell** [comment]
This refers to the specific unity-system-compositor code in LightDM. Modern versions of Mir should run under LightDM once the logind support is there. It's also my understanding that ubuports is moving away from u-s-c at some point - @khurshid-alam do you have any information about that? If ubuports is moving and they expect to be on LightDM 1.26 or older then there is no reason to keep it (I don't believe there are any other users).

@AlanGriffiths Ubuntu 18.04 will remain on 1.26 (with changes backported if required).

**Comment by AlanGriffiths** [comment]
@robert-ancell thanks for confirming that. I agree that this should have no adverse consequences given the expectation that Mir will support logind. The comments I've seen from @mariogrip (who should know) support this view.
----
A bit more detail for those that still have concerns: The UBports story is a little more nuanced than "moving away from u-s-c at some point" as there are four scenarios with different constraints:

1. **on the phone**: here they are moving from 17.04 to 16.04LTS and will continue to use lightdm & USC for the foreseeable future.
2. **on the 18.04 desktop**: here Mir-on-USC already doesn't work due to Mesa changes. They plan to use Mir's support for logind, which ought to enable use with GDM, lightdm and others without USC.
3. **on other distros**: these lack the Mesa distro patch required for Mir-on-USC. In this regard plans mirror those for Ubuntu 18.04.
4. **on the 16.04 desktop**: plans are less clear here as lightdm & USC work and the Wayland support in the majority of desktop apps is somewhat lacking. (There are also issues with the Qt version that need to be addressed.)

**Comment by mariogrip** [comment]
Just to add my two cent, I agree with the view of removal of mir-on-mir so removal of mir in lightdm makes sense. but one thing i can add is that we will loose the unity8 greeter, i'm not sure if there is other ways of getting this to work. for desktop this is acceptable, but phone this is required.

Also, We are moving from 15.04 to 16.04LTS not 17.04 on phones :)

**Comment by robert-ancell** [comment]
See https://github.com/CanonicalLtd/lightdm/pull/26

**Comment by robert-ancell** [comment]
U-S-C support was removed in 95e48f409295bc3ff9dbf3d1affd0fcd7a6d1698 (LightDM 1.29 as will be in Ubuntu 19.04).
